# Header files for POSIX standard.
# IEEE Std 1003.1-1996 (POSIX.1)
# IEEE Std 1003.2-1992 (POSIX.2)
# -=-=-=-=-=-=-=-=-=-=-=-=-
dirent.h
errno.h
fcntl.h
float.h
fmtmsg.h
fnmatch.h
glob.h
grp.h
limits.h
locale.h
math.h
netdb.h
pwd.h
regex.h
setjmp.h
signal.h
stdarg.h
stdbool.h
stddef.h
stdio.h
stdlib.h
string.h
tar.h
stermios.h
unistd.h
utime.h
wordexp.h

sys/mman.h
sys/sem.h
sys/stat.h
sys/statvfs.h
sys/times.h
sys/types.h
sys/utsname.h
sys/wait.h

netinet/in.h
netinet/tcp.h

# Posix extention
aio.h
mqueue.h
sched.h
semaphore.h
pthread.h